### ISSUE TITLE
Use NIX_PATH rather than assuming an hard coded location

### ISSUE THREAD

**Issue by shimunn** [lapp0/nix-gui#11]
Hi,

first of thanks for your great work having a soild UI would make NixOS a lot more accessible. However I still had some difficulties to get the program since it assumes an nixpkgs checkout in [`/etc/nixos/nixpkgs`](https://github.com/lapp0/nix-gui/commit/c1a4afaa0be2dc1dd8aed18f49d978bab84980f9#diff-9ce8e4e9693f0670eb3ec25eb8c410d80af03be96ac5197205ed50421f64057dR26)which I didn't have.

I got around the issue by generating `options.json` using NIX_PATH
`nix-build '<nixpkgs/nixos/release.nix>' -A options -o $HOME/.config/nixgui/release_out`

I also couldn't load my system settings since I use flakes but I'm guessing that'd be an feature for the next major version.

**Comment by lapp0** [comment]
Thanks for your bug report and the solution. I've pushed the fix. 

I'd appreciate if you continued submitting issues as you try out the program.
