### ISSUE TITLE
When using import in configuration.nix the script searches in its working directory

### ISSUE THREAD

**Issue by DerDoni** [lapp0/nix-gui#25]
My `configuration.nix` contains a the following line:

```
    shellAliases = import ./modules/aliases.nix;
```
which leads to the following error because nix-gui is searching in its own relative path:

```
INFO:error: getting status of '/home/vincenzo/Code/nix-gui/modules/aliases.nix': No such file or directory
```
The program launches regardless of the error though.

**Comment by lapp0** [comment]
This is counterintuitive logging which I kept around for my own debugging. Part of the parser recursively retrieves option values until there is an error (indicating the option cannot be evaluated using only the options scope).

This PR handles the parsing better and doesn't require an expectation that subprocess will eventually produce an error: https://github.com/lapp0/nix-gui/pull/24/

Additionally I've changed the logging level to WARNING in https://github.com/lapp0/nix-gui/commit/1ffa10d419d415de337a0b3e03fab73842ea3ea5
