### ISSUE TITLE
License

### ISSUE THREAD

**Issue by neonfuz** [lapp0/nix-gui#3]
I'm interested in contributing to this or a similar project, but license affects my decision. Can you add a license? Preferably MIT because [nixpkgs uses it](https://github.com/NixOS/nixpkgs/blob/master/COPYING).

**Comment by lapp0** [comment]
Glad to hear you're interested in contributing. Let me know how I can help.

Resolved with https://github.com/lapp0/nix-gui/commit/1bf485ef1aa6ed58bef825af1a85fc8d24cfa8f7
